/**
 * ============================================================================
 * EduQuest Content Package format (v1)
 * ============================================================================
 *
 * A *content package* is a single JSON document that supplies ALL course
 * content to the app: subjects, lessons + questions, flashcard decks + cards,
 * the reward shop, themes, achievements, stickers, arcade games, the study
 * pet, app branding, and the reward economy.
 *
 * The app ships a built-in core package, can load packages from a static
 * `/content` folder, from an uploaded file, or from Google Drive. Different
 * packages = different courses, with no code changes. The format is designed to
 * be generated by an AI: everything is plain data (achievements use declarative
 * criteria rather than code), most sections have sensible defaults, and a small
 * package (e.g. just subjects + lessons) is valid — `normalizeContentPackage`
 * fills the rest.
 *
 * User progress (currency, XP, lesson/card progress, owned items) is NOT part
 * of a content package; it lives in the user-state store and syncs separately.
 */
import type { Subject, Lesson, Flashcard, Deck, ShopItem, Theme, SubjectId, UserProfile } from '@/domain/types'
import { DEFAULT_LEVELS } from '@/domain/leveling'
import { DEFAULT_COMBO } from '@/domain/combo'
import { STREAK_MILESTONES } from '@/domain/streak'

export type {
  Subject,
  QuizQuestion,
  Lesson,
  Flashcard,
  Deck,
  ShopItem,
  Theme,
  SubjectId,
} from '@/domain/types'

export const CONTENT_FORMAT = 'eduquest-content'
export const CONTENT_FORMAT_VERSION = 1

// ---------------------------------------------------------------------------
// Stickers
// ---------------------------------------------------------------------------
export type StickerRarity = 'common' | 'rare' | 'epic' | 'shiny'

export interface Sticker {
  id: string
  name: string
  emoji: string
  rarity: StickerRarity
  collection: string
}

// ---------------------------------------------------------------------------
// Arcade mini-games (config-driven cards; "memory" is the built-in playable one)
// ---------------------------------------------------------------------------
export interface ArcadeGame {
  id: string
  title: string
  desc: string
  icon: string
  /** Hex/CSS background for the icon tile. */
  bg: string
  /** Two meta chips: [label, bg, color]. */
  tags: Array<[label: string, bg: string, color: string]>
  badge?: 'POPULAR' | 'NEW'
  /** Which built-in engine to launch. Only 'memory' is implemented today. */
  engine: 'memory' | 'none'
}

// ---------------------------------------------------------------------------
// Study pet
// ---------------------------------------------------------------------------
export interface PetConfig {
  species: string
  name: string
  /** Emoji per evolution stage (index = stage). */
  evolutionStages: Array<{ emoji: string; label: string }>
}

// ---------------------------------------------------------------------------
// Achievements — declarative so they are serializable / AI-generatable
// ---------------------------------------------------------------------------
export type AchievementStat =
  | 'lessonsCompleted'
  | 'streak'
  | 'competeWins'
  | 'coins'
  | 'xp'
  | 'ownedItems'
  | 'threeStarLessons'
  | 'perfectLessons'
  | 'masteredCards'
  | 'avgAccuracy'

export interface AchievementCriteria {
  stat: AchievementStat
  /** Earned when the computed stat is >= this value. */
  gte: number
  /** For avgAccuracy: require at least this many samples first. */
  minSamples?: number
}

export interface AchievementDef {
  id: string
  name: string
  emoji: string
  description: string
  criteria: AchievementCriteria
}

// ---------------------------------------------------------------------------
// App branding + reward economy
// ---------------------------------------------------------------------------
export interface AppConfig {
  title: string
  tagline: string
  /** Lesson id launched by the Home "Daily Challenge" banner. */
  dailyChallengeLessonId: string
}

export interface LevelBand {
  minLevel: number
  title: string
}

export interface EconomyConfig {
  startingCoins: number
  startingGems: number
  levels: {
    baseXp: number
    stepXp: number
    maxLevel: number
    bands: LevelBand[]
  }
  /** Combo tiers, ascending by minStreak. */
  combo: Array<{ minStreak: number; multiplier: number }>
  streakMilestones: number[]
  lesson: {
    xpPerCorrect: number
    perfectBonusXp: number
    perfectBonusGems: number
  }
  flashcard: {
    baseCoins: number
    coinsPerGotIt: number
    baseXp: number
    xpPerGotIt: number
    perfectBonusXp: number
    perfectGems: number
  }
  compete: {
    /** Index 0 = 1st place, etc. */
    placements: Array<{ coins: number; xp: number }>
    perfectGems: number
  }
  /** Lucky-spin prize table. */
  dailySpinPrizes: Array<{ coins?: number; gems?: number }>
}

export interface PackageMeta {
  id: string
  name: string
  description: string
  author: string
  version: string
  locale: string
  /** Emoji/icon for the pack picker. */
  cover: string
  createdAt?: string
}

// ---------------------------------------------------------------------------
// The package itself (authoring shape — most sections optional)
// ---------------------------------------------------------------------------
export interface ContentPackage {
  format: typeof CONTENT_FORMAT
  formatVersion: number
  meta: PackageMeta
  app?: Partial<AppConfig>
  economy?: DeepPartial<EconomyConfig>
  defaultProfile?: Partial<UserProfile>
  subjects: Subject[]
  lessons: Lesson[]
  decks?: Deck[]
  shopItems?: ShopItem[]
  themes?: Theme[]
  achievements?: AchievementDef[]
  stickers?: Sticker[]
  arcadeGames?: ArcadeGame[]
  pet?: PetConfig
}

type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }

// ---------------------------------------------------------------------------
// Normalized, ready-to-use content (defaults applied + index maps)
// ---------------------------------------------------------------------------
export interface LoadedContent {
  meta: PackageMeta
  app: AppConfig
  economy: EconomyConfig
  defaultProfile: UserProfile
  subjects: Subject[]
  subjectById: Record<string, Subject>
  lessons: Lesson[]
  lessonById: Record<string, Lesson>
  lessonsBySubject: Record<SubjectId, Lesson[]>
  decks: Deck[]
  deckById: Record<string, Deck>
  allCards: Flashcard[]
  cardById: Record<string, Flashcard>
  shopItems: ShopItem[]
  shopById: Record<string, ShopItem>
  themes: Theme[]
  themeById: Record<string, Theme>
  achievements: AchievementDef[]
  achievementById: Record<string, AchievementDef>
  stickers: Sticker[]
  stickerById: Record<string, Sticker>
  arcadeGames: ArcadeGame[]
  pet: PetConfig
}

// ---------------------------------------------------------------------------
// Defaults — make partial / AI-authored packages fully playable
// ---------------------------------------------------------------------------
export const DEFAULT_ECONOMY: EconomyConfig = {
  startingCoins: 100,
  startingGems: 0,
  levels: DEFAULT_LEVELS,
  combo: DEFAULT_COMBO,
  streakMilestones: STREAK_MILESTONES,
  lesson: { xpPerCorrect: 10, perfectBonusXp: 50, perfectBonusGems: 2 },
  flashcard: { baseCoins: 25, coinsPerGotIt: 5, baseXp: 50, xpPerGotIt: 10, perfectBonusXp: 100, perfectGems: 5 },
  compete: {
    placements: [
      { coins: 100, xp: 200 },
      { coins: 50, xp: 100 },
      { coins: 25, xp: 50 },
      { coins: 10, xp: 20 },
    ],
    perfectGems: 5,
  },
  dailySpinPrizes: [{ coins: 50 }, { coins: 100 }, { coins: 200 }, { gems: 2 }, { gems: 5 }, { coins: 150 }],
}

const DEFAULT_APP: AppConfig = {
  title: 'EduQuest',
  tagline: 'A learning adventure!',
  dailyChallengeLessonId: '',
}

const DEFAULT_PROFILE: UserProfile = { name: 'Explorer', avatar: '🦊', age: 8 }

const DEFAULT_PET: PetConfig = {
  species: '🐉',
  name: 'Sparky',
  evolutionStages: [
    { emoji: '🥚', label: 'Egg' },
    { emoji: '🐣', label: 'Baby' },
    { emoji: '🐲', label: 'Teen' },
    { emoji: '🐉', label: 'Adult' },
  ],
}

const DEFAULT_ARCADE: ArcadeGame[] = [
  {
    id: 'memory',
    title: 'Memory Match',
    desc: 'Find matching pairs of pictures!',
    icon: '🃏',
    bg: '#EDE7FF',
    tags: [['Memory', '#E0FFF5', 'var(--color-accent-mint)'], ['2-5 min', '#F0EEF8', 'var(--color-primary)']],
    badge: 'POPULAR',
    engine: 'memory',
  },
]

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------
export interface ValidationResult {
  ok: boolean
  errors: string[]
  warnings: string[]
}

export function validateContentPackage(input: unknown): ValidationResult {
  const errors: string[] = []
  const warnings: string[] = []
  const pkg = input as Partial<ContentPackage> | null

  if (!pkg || typeof pkg !== 'object') {
    return { ok: false, errors: ['Package is not an object'], warnings }
  }
  if (pkg.format !== CONTENT_FORMAT) {
    errors.push(`"format" must be "${CONTENT_FORMAT}" (got ${JSON.stringify(pkg.format)})`)
  }
  if (typeof pkg.formatVersion !== 'number') {
    errors.push('"formatVersion" must be a number')
  } else if (pkg.formatVersion > CONTENT_FORMAT_VERSION) {
    warnings.push(`Package formatVersion ${pkg.formatVersion} is newer than supported ${CONTENT_FORMAT_VERSION}`)
  }
  if (!pkg.meta || typeof pkg.meta.id !== 'string' || !pkg.meta.id) {
    errors.push('"meta.id" is required')
  }
  if (!pkg.meta || typeof pkg.meta.name !== 'string' || !pkg.meta.name) {
    errors.push('"meta.name" is required')
  }
  if (!Array.isArray(pkg.subjects) || pkg.subjects.length === 0) {
    errors.push('"subjects" must be a non-empty array')
  }
  if (!Array.isArray(pkg.lessons) || pkg.lessons.length === 0) {
    errors.push('"lessons" must be a non-empty array')
  }

  // Referential integrity (warnings — the app tolerates them).
  if (Array.isArray(pkg.subjects) && Array.isArray(pkg.lessons)) {
    const subjectIds = new Set(pkg.subjects.map((s) => s.id))
    for (const l of pkg.lessons) {
      if (!subjectIds.has(l.subjectId)) {
        warnings.push(`Lesson "${l.id}" references unknown subject "${l.subjectId}"`)
      }
      if (!Array.isArray(l.questions) || l.questions.length === 0) {
        errors.push(`Lesson "${l.id}" has no questions`)
      } else {
        for (const q of l.questions) {
          if (!Array.isArray(q.options) || q.options.length < 2) {
            errors.push(`Question "${q.id}" in lesson "${l.id}" needs >= 2 options`)
          } else if (q.correctIndex < 0 || q.correctIndex >= q.options.length) {
            errors.push(`Question "${q.id}" correctIndex out of range`)
          }
        }
      }
    }
  }
  if (Array.isArray(pkg.decks)) {
    for (const d of pkg.decks) {
      if (!Array.isArray(d.cards) || d.cards.length === 0) {
        warnings.push(`Deck "${d.id}" has no cards`)
      }
    }
  }

  return { ok: errors.length === 0, errors, warnings }
}

// ---------------------------------------------------------------------------
// Normalization — apply defaults and build index maps
// ---------------------------------------------------------------------------
function mergeEconomy(partial?: DeepPartial<EconomyConfig>): EconomyConfig {
  const d = DEFAULT_ECONOMY
  if (!partial) return structuredCloneSafe(d)
  return {
    startingCoins: partial.startingCoins ?? d.startingCoins,
    startingGems: partial.startingGems ?? d.startingGems,
    levels: {
      baseXp: partial.levels?.baseXp ?? d.levels.baseXp,
      stepXp: partial.levels?.stepXp ?? d.levels.stepXp,
      maxLevel: partial.levels?.maxLevel ?? d.levels.maxLevel,
      bands: (partial.levels?.bands as LevelBand[]) ?? d.levels.bands,
    },
    combo: (partial.combo as EconomyConfig['combo']) ?? d.combo,
    streakMilestones: (partial.streakMilestones as number[]) ?? d.streakMilestones,
    lesson: { ...d.lesson, ...partial.lesson },
    flashcard: { ...d.flashcard, ...partial.flashcard },
    compete: {
      placements: (partial.compete?.placements as EconomyConfig['compete']['placements']) ?? d.compete.placements,
      perfectGems: partial.compete?.perfectGems ?? d.compete.perfectGems,
    },
    dailySpinPrizes: (partial.dailySpinPrizes as EconomyConfig['dailySpinPrizes']) ?? d.dailySpinPrizes,
  }
}

function structuredCloneSafe<T>(v: T): T {
  return JSON.parse(JSON.stringify(v)) as T
}

function indexBy<T extends { id: string }>(items: T[]): Record<string, T> {
  return Object.fromEntries(items.map((i) => [i.id, i]))
}

export function normalizeContentPackage(pkg: ContentPackage): LoadedContent {
  const subjects = pkg.subjects
  const lessons = [...pkg.lessons].sort((a, b) => a.order - b.order)
  const decks = pkg.decks ?? []
  const shopItems = pkg.shopItems ?? []
  const themes = pkg.themes ?? [{ id: '', name: 'Default', emoji: '🎨', description: 'Default look', swatch: ['#6C5CE7', '#A29BFE', '#FECA57'] }]
  const achievements = pkg.achievements ?? []
  const stickers = pkg.stickers ?? []
  const arcadeGames = pkg.arcadeGames ?? DEFAULT_ARCADE
  const allCards = decks.flatMap((d) => d.cards)

  const lessonsBySubject = {} as Record<SubjectId, Lesson[]>
  for (const s of subjects) lessonsBySubject[s.id] = []
  for (const l of lessons) {
    ;(lessonsBySubject[l.subjectId] ??= []).push(l)
  }

  const app: AppConfig = { ...DEFAULT_APP, ...pkg.app }
  if (!app.dailyChallengeLessonId && lessons[0]) app.dailyChallengeLessonId = lessons[0].id

  return {
    meta: pkg.meta,
    app,
    economy: mergeEconomy(pkg.economy),
    defaultProfile: { ...DEFAULT_PROFILE, ...pkg.defaultProfile },
    subjects,
    subjectById: indexBy(subjects),
    lessons,
    lessonById: indexBy(lessons),
    lessonsBySubject,
    decks,
    deckById: indexBy(decks),
    allCards,
    cardById: indexBy(allCards),
    shopItems,
    shopById: indexBy(shopItems),
    themes,
    themeById: indexBy(themes),
    achievements,
    achievementById: indexBy(achievements),
    stickers,
    stickerById: indexBy(stickers),
    arcadeGames,
    pet: pkg.pet ?? DEFAULT_PET,
  }
}
